### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by udayh** [Xilinx/inference-server#175]
**Describe the bug**
Several broken links in the docs, see the paragraphs below
https://github.com/Xilinx/inference-server/blob/main/docs/kserve.rst#get-or-build-the-amd-inference-server-image
https://github.com/Xilinx/inference-server/blob/main/docs/kserve.rst#making-requests

**Comment by varunsh-xilinx** [comment]
The raw `.rst` files are not intended to be read directly; they are source files for the [website](https://xilinx.github.io/inference-server/main/index.html) with links that get populated during HTML generation. If there are broken links in the documentation, please point them out in the website.
