### ISSUE TITLE
readme.rst AKS link has changed due to structural changes in the Vitis AI repo

### ISSUE THREAD

**Issue by quentonh** [Xilinx/inference-server#26]
**Describe the bug**
The readme.rst provides a link to AKS which is now out of date.  The hyperlink should be changed to https://github.com/Xilinx/Vitis-AI/tree/c26eae36f034d5a2f9b2a7bfe816b8c43311a4f8/src/AKS for the VAI 2.5 release.

**To Reproduce**
Click on the AKS link in readme.rst

**Expected behavior**
Browser points to the AKS repo.

**Screenshots**
N/A

**OS/Versions:**
All

**Additional context**
Nothing to add

**Comment by varunsh-xilinx** [comment]
Thanks for the report. I updated the links in a76e177
