### ISSUE TITLE
Segmentation violation with multi-input request

### ISSUE THREAD

**Issue by bpickrel** [Xilinx/inference-server#73]
**Describe the bug**
A request created for the Migraphx worker with a bertsquad-10.onnx model (which has 4 input channels), in a Python client, led to a segmentation fault in RequestBuilder::build() 

**To Reproduce**
This happened with a new version of migraphx.cpp which accepts multiple input channels, which I have not committed yet.  It also requires a Bert model client script for migraphx.  These are the first time this I-S code has been tested with a multi-input model.

It looks like the nested for-loops at [line 346](https://github.com/Xilinx/inference-server/blob/3e80366d92f52cbacd58bd1ab320bd2dbbd4e34b/src/proteus/clients/http_internal.cpp#L346) should not be nested.  `inputs` and `buffers` both correspond 1-1 to the model's input channels.  Incrementing the reference `&offset` too many times goes beyond allocated memory.

`  for (auto const &i : inputs) {

    if (!i.isObject()) {

      throw invalid_argument("At least one element in 'inputs' is not an obj");

    }

    const auto &buffers = input_buffers;

    auto index = 0;

    for (const auto &buffer : buffers) {

      auto &offset = input_offsets[index];
`

**Comment by varunsh-xilinx** [comment]
Thanks, this was helpful to track down the problem. I think I've fixed it in [a726645](https://github.com/Xilinx/inference-server/commit/a7266457d94643051c91b5eb8859310e1938b4cf) (I made a dummy worker test case). Let me know if it also fixes what you observed.
