### ISSUE TITLE
Contiguous per-input memory for multi-input, multi-request per batch

### ISSUE THREAD

**Issue by bpickrel** [Xilinx/inference-server#79]
**Is your feature request related to a problem? Please describe.**
A worker processing a batch of input requests, for a model that uses more than 1 input channel e.g. bertsquad-10.onnx, requires there to be a single tensor for each input channel, in contiguous memory.  The 0'th dimension of the tensor is the number of items in the batch.  The Inference Server batcher, however, provides inputs in non-contiguous order.  This caused crashes in initial testing.

This problem was never observed for models with only a single input (e.g. Resnet50), apparently because all arrays for each request in a batch were located end-to-end in memory.  But for multiple inputs, the inputs are either interleaved or located in wildly different locations (my testing on this is inconclusive).

**Describe the solution you'd like**
Modify the Batcher to copy all input data for each input channel in a batch, into a single contiguous tensor array for each input containing that input channel for every request in the batch.  This should occur before the batch is added to the queue.  For example, for the channel named "input_ids:0" in a batch of n requests, the array layout would be

input_ids:0   =>     `req_0_data  |  req_1_data  |  req_2_data  |  ...`

Each of the data items may be a multidimensional tensor itself, and the full input tensor for that channel has one more dimension than each request data block.

Tensors for different input channels do not need to be contiguous since a separate pointer to each input is provided.

The input data pointer provided to the worker should be to the base address (0'th request) of the tensor for that input channel.

**Describe alternatives you've considered**
Considered adding code to the Migraphx worker to rearrange input tensors into contiguous blocks.  This is not a appropriate location for the change because this interface requirement should apply to all workers handling ONNX-compatible models alike.

**Additional context**
See attached file for a Python test script; however, I was only able to look at multi-input, multi-request batches with custom batcher code also containing a workaround for a different problem.  Also, supporting Python files and data for this script need to be fetched from the Migraphx repository.
 
[migraphx_bert.py.txt](https://github.com/Xilinx/inference-server/files/9650437/migraphx_bert.py.txt)

**Comment by varunsh-xilinx** [comment]
I'm having a little trouble following your request but let me try to understand with a more concrete example:

Consider a model requiring two input tensors of shapes `[1, 3, 3]` (Input 0) and `[3, 4, 4]` (Input 1), with flat sizes of 9 and 48 elements, respectively. First, Client A sends a request to this model with `[0, 1... 8]` and `[100, 101... 147]` for the input tensor data, respectively. Then, Client B sends a request to the same model with `[20, 21... 28]` and `[200, 201... 247]`. Let's say the batch size is 2.

Currently, the worker would be expected to create pairs of buffers in the `doAllocate()`: the first should be size 18 (9 * batch size) and the second should be 96 (48 * batch size). The data that the worker receives should be these buffers with the data like so: `[0, 1 ... 8, 20, 21 ... 28]` and `[100, 101... 147, 200, 201... 247]`.

So my questions for you are:
1. This is the intended batching behavior currently. Do you observe this happening or something else?
2. Is this the desired behavior?

**Comment by varunsh-xilinx** [comment]
Don't think about `input_buffers_` in the `doRun()`. As far as you're concerned, it doesn't exist after `doAllocate()`.

There are a few ways to access the data in the `doRun()`. Assuming the example above, with uint8s:

The batch holds the buffers:
```c++
// this gives you back a vector of Buffers for each input tensor, should be of size 2 in this case
const auto& inputs_buffers = batch->getInputBuffers();
// points to [0, 1... 28]
void* data_0 = input_buffers[0]->data();
// this should first point to the data [100, 101... 247]
void* data_1 = input_buffers[1]->data();
```

Alternatively, you can use each input, which contains a pointer to the start of that input's data in the buffer. Since the data is contiguous, looking at the first request's inputs gives you the same pointer as above. You have to use the right size though to access the data.

```c++
auto& req0 = batch->getRequest(0);
// inputs0 should be of size 2 in this case
auto inputs0 = req0->getInputs();
// this should first point to the data [0, 1... 28]
void* data_0 = inputs0[0].getData();
// this should first point to the data [100, 101... 247]
void* data_1 = inputs0[1].getData();

// if you used the second request instead, you'd get different pointers
auto& req1 = batch->getRequest(1);
// inputs1 should be of size 2 in this case
auto inputs1 = req1->getInputs();
// this should first point to the data [20, 21... 28]
void* data_0 = inputs1[0].getData();
// this should first point to the data [200, 201... 247]
void* data_1 = inputs1[1].getData();
```

Wrt to the batching, I commented on your other issue so take a look at that.

**Comment by bpickrel** [comment]
Your last comment confirms what I was looking at with yesterday's test.  Edited output follows.  The two requests had the same address for each of the 4 input channels.  Again, since I built the batch in a nonstandard way it's hard to confirm that the test itself didn't spoil the result.

> Test run with two copies of the same request forced into a batch.  Code:

> ---------
> for(size_t reqIndex = 0; reqIndex < items_in_batch; reqIndex++)
>   {    // The 0'th data pointer for the 0'th request is the base address of the
>     // whole data array for the batch
>     auto& req0 = batch->getRequest(reqIndex);
> 
>     auto inputs0 = req0->getInputs();
> 
>     auto* input_buffer = inputs0[0].getData();
> 	...
> 	
> 	--------
> 0x7f2094014040
> p input_buffer
> $6 = (void *) 0x7f201b595010                 <=== first iteration
> 
>  p input_buffer
> $7 = (void *) 0x7f201b595010                 <=== second iteration; same address
> 
> =======================================================
> 
> Same as above; looking at the different inputs for each request.  For each iteration, there are 4 input
> addresses that differ by 7 hex digits (not even close to each other) but they're the same for both requests
> 
> p req0
> $9 = std::shared_ptr<proteus::InferenceRequest> (use count 1, weak count 0) = {get() = 0x7f2094020dc0}
> 
> 0x7f7557595010
> 0x7f754ee9a6b0
> 0x7f753677cd90
> 
> 0x7f753678c080
> 
>  --
>  0x7f7557595010
>  0x7f754ee9a6b0
>  0x7f753677cd90
>  
>  0x7f753678c080
>  
>  --------------

**Comment by varunsh-xilinx** [comment]
I believe this issue is resolved so I'm closing it. Please reopen or raise a new issue if it's still a problem
