### ISSUE TITLE
migraphx scripts, feedback

### ISSUE THREAD

**Issue by bpickrel** [Xilinx/inference-server#92]
1.   The example script examples/resnet50/migraphx.py doesn't give notification if it decides to start the server locally.  Suggest the following add:

    if args.ip == "127.0.0.1" and not client.serverLive():
        print("No server detected. Starting locally...")

Starting a temporary server instance causes a huge performance penalty, so users need to know right away if a problem connecting exists.

2.  The example script examples/yolo/migraphx.py garbles the root name of its output file, ending up with "0.jpg" (low priority)
3. Feature request:  add a "batch" command line argument to all the Migraphx examples.  Batch size is a parameter that has a major effect on speed in MigraphX, and the ability to work with it and check performance will be valuable to anyone setting up a new installation.

**Comment by varunsh-xilinx** [comment]
1. Yes, that's a good idea. I'll add that
2. What do you mean by garble? It currently does just save it as an <index>.jpg in the same directory as the example script. Should it be named something else?
3. I will add that as an optional flag but the examples should not be used for performance evaluation. Or at least these ones should not be. They are intentionally simple and intended to demonstrate the API and basic functionality. Instead, we should add tests for evaluating performance with different models

**Comment by bpickrel** [comment]
> 2. What do you mean by garble? It currently does just save it as an .jpg in the same directory as the example script. Should it be named something else?

The erstwhile output filename was yolo4_output0.jpg (for example)

> 3. I will add that as an optional flag but the examples should not be used for performance evaluation. Or at least these ones should not be. They are intentionally simple and intended to demonstrate the API and basic functionality. Instead, we should add tests for evaluating performance with different models

Sounds good
