### ISSUE TITLE
Upgrade to ROCm 5.4.1 

### ISSUE THREAD

**Issue by bpickrel** [Xilinx/inference-server#98]
Reminder to raise the version number of ROCm (the package that includes Migraphx) in the docker generator to v 5.4.1.  The testing release of v5.4.1 was made public in the "hidden" repository on Dec 8.  I've verified it with the 3 Migraphx Python examples but the test script `amdinfer test` failed with message: `ERROR tests/workers/test_migraphx.py::TestMigraphx::test_migraphx[1] - amdinfer._amdinfer.BadStatus`.  I noted one bug in all three examples: inability to parse the batch-size argument from the command line.

The 5.4.1 release contains a fix to a bug that was found in the 5.4.0 release, one which seriously hampers Migraphx.

Changes for the version change and batch bug fix are as follows:

`+migraphx_apt_repo = 'echo "deb [arch=amd64 trusted=yes] https://repo.radeon.com/rocm/apt/.apt_5.4.1/ ubuntu main" > /etc/apt/sources.list.d/rocm.list'
+migraphx_yum_repo = '"[ROCm]\\nname=ROCm\\nbaseurl=https://repo.radeon.com/rocm/yum/.yum_5.4.1/main/\\nenabled=1\\ngpgcheck=1\\ngpgkey=https://repo.radeon.com/rocm/rocm.gpg.key" > /etc/yum.repos.d/rocm.repo'`

Add the following in all of  examples/bert/bert.py, examples/resnet50/resnet.py and examples/yolo/yolo.py:

`     parser.add_argument(
         "--batch-size",
         default=10,
        type=int,       <== add
         help="Batch size to use for the MIGraphX worker on the server",
     )`

Also, the production release of version 5.4.1 is expected within a few days, which will supersede this version/URL.  Note that the repository URL for the production release will not contain the `.apt_` prefix to the version number.

**Comment by varunsh-xilinx** [comment]
The 5.4.1 link is already public: https://repo.radeon.com/rocm/apt/5.4.1/. I've made these changes in the `bump-to-rocm54` branch. Can you please confirm this branch works on your end?

**Comment by bpickrel** [comment]
Do we have any further instructions for installing git-lfs?  I get an error when I run `git lfs install` on my fresh system, for reasons not clear to me.  I tried it both within and outside of the docker container.  The github lfs Web page is not very user friendly.

**Comment by bpickrel** [comment]
Looks like `sudo apt-get install git-lfs` still has to be run independent of amdinfer setup for this to work.  Can it be automated?

**Comment by varunsh-xilinx** [comment]
`git-lfs` is installed in the dev container and you can use that if you'd like. If you want it on your host machine, then it's up to you to install it, whether from `apt-get` or from the latest release on Github. We're not installing anything on the host machine right now

**Comment by bpickrel** [comment]
It may be that it did install it, but gave a warning message containing the word "Error."  Confusing.

**Comment by bpickrel** [comment]
I'm also finding that I had to run `sudo chown amdinfer-user /home/amdinfer-user` inside the Docker container before I could build the project.  This occurred on my local tower but not on my team's MI200 server.
